# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'bootsnap', '>= 1.4.2', require: false

gem "protocol-redis", git: 'https://github.com/dmitrychopey/protocol-redis', branch: 'add-sorted-sets-methods'

# Change the local async-redis to be dependend on protocol-redis with  branch: 'add-sorted-sets-methods'
gem "async-redis", path: "../../async-redis"

gem 'quiq', path: '..'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
end
